name: 'Oh No Bro!'
favicon: null
layout_spectrum: 0.04691930813714862
typography_spectrum: 0.301775615895167
title: 'Oh No Bro!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfef9'
    - '#c5b38f'
    - '#645738'
    - '#827b5b'
    - '#3e3011'
  brandStrength: 0.4375
  lightness: 0.7237024889327586
  saturation: 0.25
  rhythmicContrast: 0.6824951337184757
purpose: []
