name: 'Oh No Bro!'
favicon: null
layout_spectrum: 0.04691930813714862
typography_spectrum: 0.301775615895167
title: 'Oh No Bro!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3124173351097852
  lightness: 0.7237024889327586
  saturation: 0.14478174760006368
  rhythmicContrast: 0.6824951337184757
purpose: []
